# Workflow name
name: Daily Scheduled Job

# Trigger
on:
  # Run workflow on a schedule
  schedule:
    # Cron format:
    # minute hour day-of-month month day-of-week
    - cron: "0 0 * * *"   # Every day at midnight UTC

jobs:
  # Job name
  run-script:

    # Runner machine
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Print Message

        # Task to execute
        run: echo "Scheduled workflow executed"
